apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  labels:
    app: ocm-search
  name: search-global-config
spec:
  workload:
    manifests:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        labels:
          app: ocm-search
        name: search-global-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: global-search-user
      subjects:
      - kind: ServiceAccount
        name: search-global
        namespace: open-cluster-management-agent-addon
    - apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        labels:
          app: ocm-search
        name: search-global-hub
        namespace: open-cluster-management
      spec:
        port:
          targetPort: search-api
        tls:
          termination: passthrough
        to:
          kind: Service
          name: search-search-api
          weight: 100
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  labels:
    app: ocm-search
spec:
  installNamespace: open-cluster-management-agent-addon
---
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: search-global
  labels:
    app: ocm-search
spec:
  rotation: {}
