apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ocm-search
  name: search-global
  namespace: open-cluster-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ocm-search
  name: search-global-auto
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: global-search-user
  subjects:
  - kind: ServiceAccount
    name: search-global
    namespace: open-cluster-management
    subjects:
    - kind: ServiceAccount
      name: search-global
      namespace: open-cluster-management
---
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  labels:
    app: ocm-search
  name: search-global-config
spec:
  workload:
    manifests:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        labels:
          app: ocm-search
        name: search-global-auto
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: global-search-user
        subjects:
        - kind: ServiceAccount
          name: search-global
          namespace: open-cluster-management-managed-serviceaccount
    - apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        labels:
          app: ocm-search
        name: search-global-hub
        namespace: open-cluster-management
      spec:
        port:
          targetPort: search-api
        tls:
          termination: passthrough
        to:
          kind: Service
          name: search-search-api
          weight: 100
---
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: search-global
  labels:
    app: ocm-search
spec:
  rotation: {}
